# Generated by Django 5.1.15 on 2026-09-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='总体说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_submissions', to=settings.AUTH_USER_MODEL, verbose_name='巡检员')),
            ],
            options={
                'db_table': 'inspection_submission',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionItemResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='检查项')),
                ('result', models.CharField(choices=[('normal', '正常'), ('issue', '异常')], max_length=20, verbose_name='结果')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='问题描述')),
                ('photos', models.JSONField(default=list, verbose_name='现场照片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspection.inspectionsubmission', verbose_name='巡检提交')),
            ],
            options={
                'db_table': 'inspection_item_result',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InspectionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='任务编号')),
                ('title', models.CharField(max_length=120, verbose_name='任务名称')),
                ('period', models.CharField(choices=[('daily', '每日'), ('weekly', '每周'), ('monthly', '每月')], default='daily', max_length=20, verbose_name='巡检周期')),
                ('checklist', models.JSONField(default=list, verbose_name='检查项清单')),
                ('status', models.CharField(choices=[('pending', '待领取'), ('claimed', '巡检中'), ('submitted', '待整改'), ('returned', '复验驳回'), ('done', '已关闭')], default='pending', max_length=20, verbose_name='任务状态')),
                ('scheduled_at', models.DateTimeField(verbose_name='计划巡检时间')),
                ('due_at', models.DateTimeField(verbose_name='巡检期限')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='organization.area', verbose_name='巡检区域')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspection_tasks', to=settings.AUTH_USER_MODEL, verbose_name='当前巡检负责人')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspection_tasks', to='organization.building', verbose_name='楼栋')),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_tasks', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'db_table': 'inspection_task',
                'ordering': ['-id'],
            },
        ),
        migrations.AddField(
            model_name='inspectionsubmission',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='submission', to='inspection.inspectiontask', verbose_name='巡检任务'),
        ),
        migrations.AddIndex(
            model_name='inspectiontask',
            index=models.Index(fields=['status'], name='inspection__status_5f3c4e_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontask',
            index=models.Index(fields=['assignee', 'status'], name='inspection__assigne_32e372_idx'),
        ),
        migrations.AddIndex(
            model_name='inspectiontask',
            index=models.Index(fields=['due_at'], name='inspection__due_at_4434e9_idx'),
        ),
    ]
