# Generated by Django 5.1.15 on 2026-09-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('task', '巡检任务'), ('rectification_order', '整改单')], default='task', max_length=30, verbose_name='对象类型')),
                ('target_id', models.BigIntegerField(verbose_name='对象ID')),
                ('action', models.CharField(max_length=40, verbose_name='动作')),
                ('from_status', models.CharField(blank=True, default='', max_length=30, verbose_name='变更前状态')),
                ('to_status', models.CharField(blank=True, default='', max_length=30, verbose_name='变更后状态')),
                ('actor_name', models.CharField(blank=True, default='', max_length=40, verbose_name='操作人姓名快照')),
                ('detail', models.CharField(blank=True, default='', max_length=500, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_histories', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'db_table': 'audit_status_history',
                'ordering': ['id'],
                'indexes': [models.Index(fields=['target_type', 'target_id', 'created_at'], name='audit_statu_target__4a9d68_idx')],
            },
        ),
    ]
