# Generated by Django 5.1.15 on 2026-09-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('task', '巡检任务'), ('rectification_order', '整改单')], default='task', max_length=30, verbose_name='对象类型')),
                ('target_id', models.BigIntegerField(verbose_name='对象ID')),
                ('level', models.CharField(choices=[('supervisor', '主管')], default='supervisor', max_length=20, verbose_name='升级级别')),
                ('reason', models.CharField(max_length=200, verbose_name='升级原因')),
                ('overdue_at', models.DateTimeField(blank=True, null=True, verbose_name='超期时点')),
                ('status', models.CharField(choices=[('open', '待处置'), ('resolved', '已处置')], default='open', max_length=20, verbose_name='状态')),
                ('handle_note', models.CharField(blank=True, default='', max_length=500, verbose_name='处置说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处置时间')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_escalations', to=settings.AUTH_USER_MODEL, verbose_name='触发人')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_escalations', to=settings.AUTH_USER_MODEL, verbose_name='处置主管')),
            ],
            options={
                'db_table': 'escalation_escalation',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['status', 'target_type', 'target_id'], name='escalation__status_3b4805_idx')],
            },
        ),
    ]
