# Generated by Django 5.1.15 on 2026-09-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inspection', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RectificationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='整改单号')),
                ('source', models.CharField(choices=[('inspection', '巡检提交'), ('recheck', '复验驳回')], default='inspection', max_length=20, verbose_name='来源类型')),
                ('source_item_name', models.CharField(max_length=120, verbose_name='来源检查项')),
                ('issue_description', models.CharField(max_length=500, verbose_name='问题描述')),
                ('severity', models.CharField(choices=[('low', '一般'), ('medium', '较重'), ('high', '严重')], default='medium', max_length=20, verbose_name='严重程度')),
                ('issue_photos', models.JSONField(default=list, verbose_name='问题照片（来源快照）')),
                ('status', models.CharField(choices=[('pending', '待整改'), ('processing', '整改中'), ('submitted', '待复验'), ('returned', '复验驳回'), ('verified', '复验通过'), ('closed', '已关闭')], default='pending', max_length=20, verbose_name='整改单状态')),
                ('round', models.PositiveIntegerField(default=1, verbose_name='整改轮次')),
                ('due_at', models.DateTimeField(verbose_name='整改期限')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='领取时间')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='最近提交时间')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='复验通过时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectification_orders', to=settings.AUTH_USER_MODEL, verbose_name='当前整改负责人')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rectification_orders', to='inspection.inspectiontask', verbose_name='来源巡检任务')),
            ],
            options={
                'db_table': 'rectification_order',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RecheckRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(verbose_name='复验轮次')),
                ('passed', models.BooleanField(verbose_name='是否通过')),
                ('note', models.CharField(blank=True, default='', max_length=500, verbose_name='复验说明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inspector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechecks', to=settings.AUTH_USER_MODEL, verbose_name='复验巡检员')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechecks', to='rectification.rectificationorder', verbose_name='整改单')),
            ],
            options={
                'db_table': 'rectification_recheck',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RectificationResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField(verbose_name='整改轮次')),
                ('note', models.CharField(max_length=500, verbose_name='处理说明')),
                ('photos', models.JSONField(default=list, verbose_name='处理后照片')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resolutions', to='rectification.rectificationorder', verbose_name='整改单')),
                ('rectifier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rectification_resolutions', to=settings.AUTH_USER_MODEL, verbose_name='整改人')),
            ],
            options={
                'db_table': 'rectification_resolution',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='rectificationorder',
            index=models.Index(fields=['status'], name='rectificati_status_008ffa_idx'),
        ),
        migrations.AddIndex(
            model_name='rectificationorder',
            index=models.Index(fields=['assignee', 'status'], name='rectificati_assigne_474aee_idx'),
        ),
        migrations.AddIndex(
            model_name='rectificationorder',
            index=models.Index(fields=['due_at'], name='rectificati_due_at_049b48_idx'),
        ),
    ]
