# Generated by Django 5.1.15 on 2026-09-15 13:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True, verbose_name='登录名')),
                ('name', models.CharField(max_length=40, verbose_name='姓名')),
                ('role', models.CharField(choices=[('property', '物业管理员'), ('inspector', '巡检员'), ('rectifier', '整改人'), ('supervisor', '主管')], default='inspector', max_length=20, verbose_name='角色')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='联系电话')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users_user',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='令牌')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'db_table': 'users_auth_token',
            },
        ),
    ]
