# Generated by Django 5.1.15 on 2026-09-15 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='楼栋编号')),
                ('name', models.CharField(max_length=80, verbose_name='楼栋名称')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'org_building',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, verbose_name='区域编号')),
                ('name', models.CharField(max_length=80, verbose_name='区域名称')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='位置描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='organization.building', verbose_name='所属楼栋')),
            ],
            options={
                'db_table': 'org_area',
                'ordering': ['building__code', 'code'],
                'unique_together': {('building', 'code')},
            },
        ),
    ]
